title:              뀔뀔(swieeft)의 개발새발기
email:              swieeft89@gmail.com
description:        달콤한 개발을 꿈꾸는 개발자
author:             swieeft
baseurl:            ""
url:                "https://swieeft.github.io"

# Social Profiles
twitter_username:
github_username:    swieeft
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-158807306-1 # out your google-analytics code
  
sass:
  sass_dir:         _sass
  style:            styles
  
gist:
  noscript: false
  
# Build settings
markdown:           kramdown
asset_url:          /assets
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
